from typing import Protocol as ProtocolistProtocol
from typing import runtime_checkable
@runtime_checkable
class Arg1(ProtocolistProtocol):
	def __add__(self, other):
		...
	def __divmod__(self, other):
		...
	def __floordiv__(self, other):
		...
	def __mul__(self, other):
		...
	def __pow__(self, exponent, modulus=None):
		...
	def __sub__(self, other):
		...
	def __truediv__(self, other):
		...
